void main (){
  String ilce = "Atakum";
  String kita = "Asya";
  String faks = "05469995599";
  int postaKodu = 55200;
  String instaAdress ="furkannaric";
  String calistiginBolum = "sofware";
  int urunMiktari = 800;
  String musteriSoyadi = "Aric";
  double odemeMiktari = 999.99;
  String dogumTarihi ="9/8/97";
  double borc = 700.00;
  bool medeniHal = true;
  String videoYorumu = "Çok güzel.";
  String odemeSaati = "14.30";
  double eftMiktari = 99.80;
  int satilanMiktar = 24;
  String telefonModeli = "Samsung E250";
  String dergiAdi = "Finans Nabzı";
  String basimTarihi = "19.12.23";
  double zamMiktari = 0.45;
  int daireSayisi = 3;
  double enlem = 41.0372623 ;
  double boylam = -126.54708;
  String yemekAdi = "Karnıyarık";
  double urunFiyati = 300.00;
  String sirket = "ARC";
  String videoAdi = "flutter ";
  String muzikSuresi = "280 sn ";
  String mekanAdi = "Kosmos";
  double mekanPuani = 9.7;
  String dosyaAdi = "Fezdeke";
  String resimFormati = ".jpg";
  String renk = "Kırmızı";
  int renkKodu = 90034;
  String pcModeli = "Asus x890";
  double ekranBoyutu = 15.6;
  double kullanimSuresi = 1568.2;
  double basinc = 3.43;
  String etkinlikGunu ="pazartesi ";
  String odemeGunu = "salı";
  String yolculukCikisTarihi = "9/8/97";
  String mahalleAdi = "Akyazı";
  String otobusHatti = "E24";
  double kullanilanDakika = 89.1;
  int kargoTakipNo = 1548692455;
  int kuponSuresi =7;
  int kuponKodu = 12547;
  String faturaTarihi = "09.07.2023";

  print("ilçe : $ilce");
  print("Kıta : $kita");
  print("Faks No : $faks");
  print("Posta Kodu : $postaKodu");
  print("İnstagram Adresi : $instaAdress");
  print("Çalıstıgın Bölüm : $calistiginBolum");
  print("Ürün Miktarı : $urunMiktari");
  print("Müsteri Soyadı: $musteriSoyadi");
  print("Ödeme Miktarı : $odemeMiktari");
  print("Doğum Tarihi : $dogumTarihi");
  print("Borç : $borc");
  print("MedeniHali : $medeniHal");
  print("video Yorumu : $videoYorumu");
  print("Ödeme Saati : $odemeSaati");
  print("Eft Miktarı : $eftMiktari");
  print("Satılan Miktar : $satilanMiktar");
  print("Telefon Modeli : $telefonModeli");
  print("Dergi Adı : $dergiAdi");
  print("Basım Tarihi: $basimTarihi");
  print("Zam Miktarı : $zamMiktari");
  print("Daire Sayısı : $daireSayisi");
  print("Enlem: $enlem");
  print("Boylam: $boylam");
  print("Yemek AdI : $yemekAdi");
  print("ürün Fiyatı : $urunFiyati");
  print("Şirket : $sirket");
  print("Video Adı : $videoAdi");
  print("Müzik Süresi : $muzikSuresi");
  print("Mekan Adı: $mekanAdi");
  print("Mekan Puanı : $mekanPuani");
  print("Dosya Adı : $dosyaAdi");
  print("Resim Formatı : $resimFormati");
  print("Renk: $renk");
  print("Renk Kodu : $renkKodu");
  print("Pc Modeli : $pcModeli");
  print("Ekran Boyutu : $ekranBoyutu");
  print("Kullanım Süresi : $kullanimSuresi");
  print("Basınç : $basinc");
  print("Etkinlik Günü : $etkinlikGunu");
  print("Ödeme Günü : $odemeGunu");
  print("Yolculuk Çıkış Tarihi : $yolculukCikisTarihi");
  print("Mahalle Adı : $mahalleAdi");
  print("Otobüs Hattı : $otobusHatti");
  print("Kullanılan Dakika : $kullanilanDakika");
  print("kargo Takip No: $kargoTakipNo");
  print("Kupon Süresi: $kuponSuresi");
  print("Kupon Kodu : $kuponKodu");
  print("Fatura Tarihi : $faturaTarihi");

}